@echo off
chcp 65001 >nul
setlocal
set "DIR=%~dp0"
set "SCRIPT=%DIR%trigger-cards.bat"

rem ============================================================
rem  Keep this file pure ASCII - cmd.exe reads .bat in the OEM
rem  codepage and UTF-8 Chinese text shatters the parser.
rem  Task names are ASCII too, so schtasks /Query and /Delete
rem  always match regardless of console codepage.
rem ============================================================

echo ============================================================
echo   Install ClaudeAtelier card-trigger scheduled tasks
echo ============================================================
echo.
echo   The deepseek workflows carry a cron, but GitHub runs it
echo   late every time - 47 min to 2 h 33 min in 7 measured
echo   runs. A workflow_dispatch skips that queue and starts in
echo   seconds. These tasks send the dispatch.
echo.
echo   The card is still BUILT on GitHub. Only the clock moves
echo   here. Nothing generated by a model ever runs on this
echo   machine, which is the point.
echo.
echo   Two tasks will be created, matching the crons they front:
echo     1) 00:00 then every 4 hours  - deepseek-card.yml
echo     2) 00:20 then every 4 hours  - deepseek-pro-card.yml
echo.
echo   The crons stay in place as a backstop. If this machine is
echo   asleep or gh is logged out, the card is still made, just
echo   late - the same as before these tasks existed.
echo.
echo   Firing at :00 and :20 is deliberate: the Claude agent owns
echo   :09 - :17 and the sync task owns :30. This script touches
echo   no file inside the repo, so it cannot collide with them.
echo.
echo   Run `gh auth status` first and make sure it says logged
echo   in. These tasks read the token from the Windows
echo   Credential Manager and run as you, only while you are
echo   logged on. No admin rights needed - and do NOT add
echo   /RU SYSTEM, SYSTEM cannot read that token.
echo.
pause

schtasks /Create /TN "ClaudeAtelier-Trigger-Flash" /TR "\"%SCRIPT%\" deepseek-card.yml"     /SC DAILY /ST 00:00 /RI 240 /DU 24:00 /F
schtasks /Create /TN "ClaudeAtelier-Trigger-Pro"   /TR "\"%SCRIPT%\" deepseek-pro-card.yml" /SC DAILY /ST 00:20 /RI 240 /DU 24:00 /F

echo.
echo ---- registered tasks ----
schtasks /Query /TN "ClaudeAtelier-Trigger-Flash"
schtasks /Query /TN "ClaudeAtelier-Trigger-Pro"

echo.
echo   Done. Log file: trigger.log
echo.
echo   Check it worked:
echo     schtasks /Query /TN "ClaudeAtelier-Trigger-Flash" /V /FO LIST
echo     ^(Last Result 0 = dispatched, anything else = see trigger.log^)
echo.
echo   To uninstall:
echo     schtasks /Delete /TN "ClaudeAtelier-Trigger-Flash" /F
echo     schtasks /Delete /TN "ClaudeAtelier-Trigger-Pro" /F
echo.
pause
